import chalk from "chalk";
import { getStyle } from "./registry.js";

const isTTY = (process.stdout.isTTY ?? false) && (process.stdin.isTTY ?? false);

export function jsonOut(data: unknown): void {
  process.stdout.write(JSON.stringify(data, null, 2) + "\n");
}

export function severityColor(sev: string): string {
  switch (sev) {
    case "critical": return chalk.red(sev);
    case "warning":  return chalk.yellow(sev);
    case "info":     return chalk.blue(sev);
    default:         return sev;
  }
}

export function statusColor(status: string): string {
  switch (status) {
    case "pass": return chalk.green(status);
    case "warn": return chalk.yellow(status);
    case "fail": return chalk.red(status);
    default:     return status;
  }
}

export function error(msg: string, suggestions?: string[]): never {
  if (isTTY) {
    console.error(chalk.red("✖ " + msg));
    if (suggestions?.length) {
      console.error(chalk.dim("  Suggestions: " + suggestions.join(", ")));
    }
  } else {
    jsonOut({ error: msg, suggestions: suggestions ?? [] });
  }
  process.exit(1);
}

export function formatAgo(ts: number | null | undefined): string | null {
  if (ts == null) return null;
  const diffMs = Date.now() - ts;
  const diffSec = Math.floor(diffMs / 1000);
  if (diffSec < 60) return `${diffSec}s ago`;
  const diffMin = Math.floor(diffSec / 60);
  if (diffMin < 60) return `${diffMin}min ago`;
  const diffHr = Math.floor(diffMin / 60);
  if (diffHr < 24) return `${diffHr}h ago`;
  const diffDay = Math.floor(diffHr / 24);
  return `${diffDay}d ago`;
}

export function buildStyleMdContent(styleName: string): string {
  const meta = getStyle(styleName);
  if (!meta) return `# Style: ${styleName}\n`;

  const lines = [
    `# Style: ${meta.displayName}`,
    ``,
    `**Category:** ${meta.category}`,
    ``,
    `## Description`,
    ``,
    meta.description,
    ``,
    `## Principles`,
    ``,
    ...meta.principles.map((p) => `- ${p}`),
    ``,
    `## Tags`,
    ``,
    meta.tags.join(", "),
    ``,
    `---`,
    `*Generated by open-styles*`,
  ];
  return lines.join("\n");
}
