#!/usr/bin/env bun
import React from "react";
import { render } from "ink";
import { Command } from "commander";
import chalk from "chalk";
import { resolve, join, dirname } from "path";
import { existsSync, mkdirSync } from "fs";
import { fileURLToPath } from "url";

import {
  STYLES,
  getStyle,
  searchStyles,
  getStylesByCategory,
  findSimilarStyles,
  CATEGORIES,
} from "../lib/registry.js";
import {
  createProfile,
  getProfile,
  getProfileByName,
  listProfiles,
  deleteProfile,
  setActiveProfile,
  getActiveProfile,
  getBuiltinStyleProfile,
} from "../lib/profiles.js";
import { getPref, setPref, listPrefs } from "../lib/preferences.js";
import { runHealthCheck, checkFile, getDefaultRules } from "../lib/health.js";
import {
  injectStyleHook,
  isHookInstalled,
} from "../lib/hookmanager.js";
import {
  initProjectDir,
  writeStyleContextFile,
  setProjectConfig,
  getProjectConfig,
} from "../lib/fs.js";
import { listTemplates, applyTemplate } from "../lib/templates.js";
import { createTasksFromViolations } from "../lib/taskgen.js";
import { App } from "./components/App.js";

// ── TTY detection ─────────────────────────────────────────────────────────────

const isTTY = (process.stdout.isTTY ?? false) && (process.stdin.isTTY ?? false);

// ── Helpers ───────────────────────────────────────────────────────────────────

function jsonOut(data: unknown): void {
  process.stdout.write(JSON.stringify(data, null, 2) + "\n");
}

function severityColor(sev: string): string {
  switch (sev) {
    case "critical":
      return chalk.red(sev);
    case "warning":
      return chalk.yellow(sev);
    case "info":
      return chalk.blue(sev);
    default:
      return sev;
  }
}

function statusColor(status: string): string {
  switch (status) {
    case "pass":
      return chalk.green(status);
    case "warn":
      return chalk.yellow(status);
    case "fail":
      return chalk.red(status);
    default:
      return status;
  }
}

function error(msg: string, suggestions?: string[]): never {
  if (isTTY) {
    console.error(chalk.red("✖ " + msg));
    if (suggestions?.length) {
      console.error(chalk.dim("  Suggestions: " + suggestions.join(", ")));
    }
  } else {
    jsonOut({ error: msg, suggestions: suggestions ?? [] });
  }
  process.exit(1);
}

// ── Build style.md content from a style name ─────────────────────────────────

function buildStyleMdContent(styleName: string): string {
  const meta = getStyle(styleName);
  if (!meta) return `# Style: ${styleName}\n`;

  const lines = [
    `# Style: ${meta.displayName}`,
    ``,
    `**Category:** ${meta.category}`,
    ``,
    `## Description`,
    ``,
    meta.description,
    ``,
    `## Principles`,
    ``,
    ...meta.principles.map((p) => `- ${p}`),
    ``,
    `## Tags`,
    ``,
    meta.tags.join(", "),
    ``,
    `---`,
    `*Generated by open-styles*`,
  ];
  return lines.join("\n");
}

// ── Program ───────────────────────────────────────────────────────────────────

const program = new Command();

program
  .name("styles")
  .description("Open Styles — design style management for AI coding agents")
  .version("0.0.1");

// ── styles list ───────────────────────────────────────────────────────────────

program
  .command("list")
  .description("List all available styles")
  .option("-c, --category <cat>", "Filter by category")
  .action(async (opts: { category?: string }) => {
    let styles = STYLES;

    if (opts.category) {
      styles = getStylesByCategory(opts.category);
      if (styles.length === 0) {
        const validCats = CATEGORIES.join(", ");
        error(`No styles found for category "${opts.category}"`, [
          `Valid categories: ${validCats}`,
        ]);
      }
    }

    if (!isTTY) {
      jsonOut(styles);
      return;
    }

    // TTY: render browsable Ink component
    const { waitUntilExit } = render(<App styles={styles} />);
    await waitUntilExit();
  });

// ── styles info ───────────────────────────────────────────────────────────────

program
  .command("info <name>")
  .description("Show full info for a style")
  .action((name: string) => {
    const style = getStyle(name);
    if (!style) {
      const similar = findSimilarStyles(name);
      error(`Style not found: "${name}"`, similar.length ? [`Did you mean: ${similar.join(", ")}`] : undefined);
    }

    if (!isTTY) {
      jsonOut(style);
      return;
    }

    console.log();
    console.log(chalk.bold.cyan(style.displayName));
    console.log(chalk.dim(`Category: ${style.category}`));
    console.log();
    console.log(style.description);
    console.log();
    console.log(chalk.bold("Principles:"));
    for (const p of style.principles) {
      console.log(`  ${chalk.cyan("•")} ${p}`);
    }
    console.log();
    console.log(chalk.dim("Tags: " + style.tags.join(", ")));
    console.log();
  });

// ── styles use ────────────────────────────────────────────────────────────────

program
  .command("use <name>")
  .description("Set the active style for a project or globally")
  .option("-p, --project <path>", "Project path (default: cwd)")
  .option("-g, --global", "Set as global default instead of project-specific")
  .action(async (name: string, opts: { project?: string; global?: boolean }) => {
    const style = getStyle(name);
    if (!style) {
      const similar = findSimilarStyles(name);
      error(`Style not found: "${name}"`, similar.length ? [`Did you mean: ${similar.join(", ")}`] : undefined);
    }

    const profile = getBuiltinStyleProfile(name);
    const projectPath = resolve(opts.project ?? process.cwd());

    if (opts.global) {
      setPref("active_profile", profile.id, "global");
      if (isTTY) {
        console.log(chalk.green(`✔ Global style set to: ${style.displayName}`));
      } else {
        jsonOut({ ok: true, scope: "global", style: name, profileId: profile.id });
      }
      return;
    }

    // Project-scoped: upsert project_configs
    setActiveProfile(projectPath, profile.id);

    // Write .styles/style.md context file into the project
    const styleContent = buildStyleMdContent(name);
    writeStyleContextFile(projectPath, styleContent);

    // Inject hook if .claude/ exists
    const claudeDir = join(projectPath, ".claude");
    if (existsSync(claudeDir)) {
      const result = injectStyleHook(projectPath);
      if (isTTY && !result.alreadyInstalled) {
        console.log(chalk.dim("  Hook injected into .claude/settings.json"));
      }
    }

    if (isTTY) {
      console.log(chalk.green(`✔ Active style set to: ${style.displayName}`));
      console.log(chalk.dim(`  Project: ${projectPath}`));
      console.log(chalk.dim(`  Context file written: ${join(projectPath, ".styles", "style.md")}`));
    } else {
      jsonOut({
        ok: true,
        scope: "project",
        project: projectPath,
        style: name,
        profileId: profile.id,
      });
    }
  });

// ── styles init ───────────────────────────────────────────────────────────────

program
  .command("init")
  .description("Initialize open-styles for a project")
  .option("-p, --project <path>", "Project path (default: cwd)")
  .option("-s, --style <name>", "Style to activate")
  .action(async (opts: { project?: string; style?: string }) => {
    const projectPath = resolve(opts.project ?? process.cwd());

    // Init project dirs in ~/.styles/
    initProjectDir(projectPath);

    // Write project.json
    const existingConfig = getProjectConfig(projectPath);
    setProjectConfig(projectPath, {
      projectPath,
      profileId: existingConfig?.profileId ?? null,
      activeTemplateId: existingConfig?.activeTemplateId ?? null,
      customOverrides: existingConfig?.customOverrides ?? {},
      hookInstalled: existingConfig?.hookInstalled ?? false,
      updatedAt: Date.now(),
    });

    // Create .styles/ dir in project
    const stylesDir = join(projectPath, ".styles");
    if (!existsSync(stylesDir)) {
      mkdirSync(stylesDir, { recursive: true });
    }

    // Write style.md if style specified
    if (opts.style) {
      const style = getStyle(opts.style);
      if (!style) {
        const similar = findSimilarStyles(opts.style);
        error(`Style not found: "${opts.style}"`, similar.length ? [`Did you mean: ${similar.join(", ")}`] : undefined);
      }
      const profile = getBuiltinStyleProfile(opts.style);
      setActiveProfile(projectPath, profile.id);
      writeStyleContextFile(projectPath, buildStyleMdContent(opts.style));
    }

    // Inject hook if .claude/ exists
    const claudeDir = join(projectPath, ".claude");
    if (existsSync(claudeDir)) {
      injectStyleHook(projectPath);
    }

    if (isTTY) {
      console.log(chalk.green(`✔ Initialized open-styles for: ${projectPath}`));
      if (opts.style) {
        console.log(chalk.dim(`  Active style: ${opts.style}`));
      }
      if (existsSync(claudeDir)) {
        console.log(chalk.dim("  Hook injected into .claude/settings.json"));
      }
    } else {
      jsonOut({
        ok: true,
        projectPath,
        style: opts.style ?? null,
        hookInjected: existsSync(claudeDir),
      });
    }
  });

// ── styles profile ────────────────────────────────────────────────────────────

const profileCmd = program.command("profile").description("Manage style profiles");

profileCmd
  .command("list")
  .description("List all custom profiles")
  .action(() => {
    const profiles = listProfiles();
    if (!isTTY) {
      jsonOut(profiles);
      return;
    }
    if (profiles.length === 0) {
      console.log(chalk.dim("No custom profiles found."));
      return;
    }
    console.log(chalk.bold("Custom Profiles:"));
    for (const p of profiles) {
      console.log(
        `  ${chalk.cyan(p.name.padEnd(20))} ${chalk.dim(p.category.padEnd(16))} ${p.displayName}`
      );
    }
  });

profileCmd
  .command("create")
  .description("Create a custom profile")
  .requiredOption("-n, --name <n>", "Profile name (slug)")
  .requiredOption("--display-name <dn>", "Display name")
  .requiredOption("-c, --category <cat>", "Category")
  .option("-d, --description <d>", "Description")
  .action((opts: { name: string; displayName: string; category: string; description?: string }) => {
    const profile = createProfile({
      name: opts.name,
      displayName: opts.displayName,
      description: opts.description ?? "",
      category: opts.category,
      principles: [],
      antiPatterns: [],
      typography: {},
      colors: {},
      componentRules: {},
      tags: [],
    });

    if (!isTTY) {
      jsonOut(profile);
      return;
    }
    console.log(chalk.green(`✔ Profile created: ${profile.name} (${profile.id})`));
  });

profileCmd
  .command("get <id-or-name>")
  .description("Get a profile by ID or name")
  .action((idOrName: string) => {
    const profile = getProfile(idOrName) ?? getProfileByName(idOrName);
    if (!profile) {
      error(`Profile not found: "${idOrName}"`);
    }
    if (!isTTY) {
      jsonOut(profile);
      return;
    }
    console.log(chalk.bold(profile.displayName));
    console.log(chalk.dim(`ID: ${profile.id}`));
    console.log(chalk.dim(`Category: ${profile.category}`));
    if (profile.description) console.log(profile.description);
    if (profile.principles.length) {
      console.log(chalk.bold("\nPrinciples:"));
      for (const p of profile.principles) console.log(`  • ${p}`);
    }
  });

profileCmd
  .command("delete <id>")
  .description("Delete a custom profile")
  .action((id: string) => {
    deleteProfile(id);
    if (!isTTY) {
      jsonOut({ ok: true, deleted: id });
      return;
    }
    console.log(chalk.green(`✔ Profile deleted: ${id}`));
  });

// ── styles prefs ──────────────────────────────────────────────────────────────

const prefsCmd = program.command("prefs").description("Manage preferences");

prefsCmd
  .command("list")
  .description("List all preferences")
  .option("-p, --project <path>", "Project path")
  .action((opts: { project?: string }) => {
    const projectPath = opts.project ? resolve(opts.project) : undefined;
    const prefs = listPrefs(projectPath);
    if (!isTTY) {
      jsonOut(prefs);
      return;
    }
    if (prefs.length === 0) {
      console.log(chalk.dim("No preferences set."));
      return;
    }
    for (const p of prefs) {
      console.log(
        `  ${chalk.cyan(p.key.padEnd(30))} ${chalk.dim(p.scope.padEnd(10))} ${p.value}`
      );
    }
  });

prefsCmd
  .command("set <key> <value>")
  .description("Set a preference value")
  .option("-p, --project <path>", "Project path")
  .option("-g, --global", "Set as global preference")
  .action((key: string, value: string, opts: { project?: string; global?: boolean }) => {
    const scope: "global" | "project" = opts.global ? "global" : "project";
    const projectPath = opts.project ? resolve(opts.project) : (scope === "project" ? process.cwd() : undefined);

    setPref(key, value, scope, projectPath);

    if (!isTTY) {
      jsonOut({ ok: true, key, value, scope });
      return;
    }
    console.log(chalk.green(`✔ Set ${scope} preference: ${key} = ${value}`));
  });

prefsCmd
  .command("get <key>")
  .description("Get a preference value")
  .option("-p, --project <path>", "Project path")
  .action((key: string, opts: { project?: string }) => {
    const projectPath = opts.project ? resolve(opts.project) : undefined;
    const value = getPref(key, projectPath);
    if (!isTTY) {
      jsonOut({ key, value });
      return;
    }
    if (value === null) {
      console.log(chalk.dim(`No value set for key: ${key}`));
    } else {
      console.log(`${chalk.cyan(key)}: ${value}`);
    }
  });

// ── styles health ─────────────────────────────────────────────────────────────

program
  .command("health")
  .description("Run a health check on the project")
  .option("-p, --project <path>", "Project path (default: cwd)")
  .option("--ai", "Use Cerebras AI for deeper analysis")
  .option("--watch", "Re-run on file changes")
  .option("--create-tasks", "Auto-create todos tasks for violations")
  .action(async (opts: { project?: string; ai?: boolean; watch?: boolean; createTasks?: boolean }) => {
    const projectPath = resolve(opts.project ?? process.cwd());

    async function doCheck() {
      const result = await runHealthCheck(projectPath);

      if (opts.ai) {
        // AI inspection via Cerebras
        const { isCerebrasAvailable, inspectProject } = await import("../lib/inspector.js");
        if (isCerebrasAvailable()) {
          if (isTTY) console.log(chalk.dim("Running AI inspection..."));
          const aiResults = await inspectProject(projectPath);
          // Merge AI violations into result for display
          for (const r of aiResults) {
            for (const v of r.violations) {
              result.violations.push({
                filePath: r.filePath,
                rule: v.rule,
                message: v.message,
                severity: v.severity,
                line: v.line,
              });
            }
          }
        } else if (isTTY) {
          console.log(chalk.yellow("CEREBRAS_API_KEY not set — skipping AI inspection"));
        }
      }

      if (opts.createTasks) {
        const tasks = await createTasksFromViolations(result.violations, projectPath);
        if (isTTY && tasks.length > 0) {
          console.log(chalk.dim(`\nCreated ${tasks.length} task(s) for violations`));
        }
      }

      if (!isTTY) {
        jsonOut(result);
        return;
      }

      // TTY: formatted table output
      console.log();
      console.log(
        `${chalk.bold("Health Check")}  ${statusColor(result.status)}  Score: ${chalk.bold(String(result.score))}/100`
      );
      console.log(chalk.dim(`Files scanned: ${result.filesScanned}`));
      console.log(chalk.dim(`Violations: ${result.violations.length}`));
      console.log();

      if (result.violations.length === 0) {
        console.log(chalk.green("✔ No violations found!"));
        return;
      }

      // Group by severity
      const bySeverity = new Map<string, typeof result.violations>();
      for (const v of result.violations) {
        const existing = bySeverity.get(v.severity) ?? [];
        existing.push(v);
        bySeverity.set(v.severity, existing);
      }

      for (const severity of ["critical", "warning", "info"]) {
        const viols = bySeverity.get(severity);
        if (!viols?.length) continue;
        console.log(`${severityColor(severity).toUpperCase()} (${viols.length}):`);
        for (const v of viols.slice(0, 10)) {
          const relPath = v.filePath.replace(projectPath + "/", "");
          console.log(`  ${chalk.dim(relPath)} — ${chalk.dim(v.rule)}`);
          console.log(`    ${v.message}`);
        }
        if (viols.length > 10) {
          console.log(chalk.dim(`  ... and ${viols.length - 10} more`));
        }
        console.log();
      }
    }

    await doCheck();

    if (opts.watch) {
      if (isTTY) console.log(chalk.dim("\nWatching for changes... (Ctrl-C to stop)"));
      setInterval(async () => {
        if (isTTY) console.log(chalk.dim("\n--- Re-running health check ---"));
        await doCheck();
      }, 10_000);
    }
  });

// ── styles check-file ─────────────────────────────────────────────────────────

program
  .command("check-file <file>")
  .description("Check a single file for style violations")
  .option("-p, --project <path>", "Project path (default: cwd)")
  .option("-q, --quiet", "Only exit code (0=pass, 1=violations)")
  .action(async (file: string, opts: { project?: string; quiet?: boolean }) => {
    const projectPath = resolve(opts.project ?? process.cwd());
    const filePath = resolve(file);

    const { getActiveProfile } = await import("../lib/profiles.js");
    const profile = getActiveProfile(projectPath);
    const rules = getDefaultRules(profile);
    const violations = checkFile(filePath, rules);

    if (opts.quiet) {
      process.exit(violations.length > 0 ? 1 : 0);
    }

    if (!isTTY) {
      jsonOut({ filePath, violations });
      return;
    }

    if (violations.length === 0) {
      console.log(chalk.green(`✔ ${file}: No violations`));
      return;
    }

    console.log(chalk.yellow(`${file}: ${violations.length} violation(s)`));
    for (const v of violations) {
      console.log(`  [${severityColor(v.severity)}] ${chalk.dim(v.rule)}: ${v.message}`);
    }
    process.exit(1);
  });

// ── styles template ───────────────────────────────────────────────────────────

const templateCmd = program.command("template").description("Manage style templates");

templateCmd
  .command("list")
  .description("List all templates")
  .option("--profile <id>", "Filter by profile ID")
  .action((opts: { profile?: string }) => {
    const templates = listTemplates(opts.profile);
    if (!isTTY) {
      jsonOut(templates);
      return;
    }
    if (templates.length === 0) {
      console.log(chalk.dim("No templates found."));
      return;
    }
    for (const t of templates) {
      console.log(`  ${chalk.cyan(t.id.slice(0, 8))}  ${t.name.padEnd(24)} ${chalk.dim(t.description)}`);
    }
  });

templateCmd
  .command("apply <id>")
  .description("Apply a template to a project")
  .option("-p, --project <path>", "Project path (default: cwd)")
  .action((id: string, opts: { project?: string }) => {
    const projectPath = resolve(opts.project ?? process.cwd());
    const result = applyTemplate(id, projectPath);

    if (!isTTY) {
      jsonOut(result);
      return;
    }

    if (result.success) {
      console.log(chalk.green(`✔ Template applied`));
      for (const f of result.filesCreated) {
        console.log(chalk.dim(`  created: ${f}`));
      }
    } else {
      console.log(chalk.red("✖ Template apply failed"));
      for (const e of result.errors) {
        console.log(chalk.red(`  ${e}`));
      }
      process.exit(1);
    }
  });

// ── styles serve ──────────────────────────────────────────────────────────────

program
  .command("serve")
  .description("Start the HTTP dashboard server")
  .option("--port <n>", "Port number", "3421")
  .action(async (opts: { port: string }) => {
    const port = parseInt(opts.port, 10);
    if (isTTY) {
      console.log(chalk.dim(`Starting dashboard server on port ${port}...`));
    }
    // Run the server as a subprocess via bun
    const proc = Bun.spawn(["bun", "run", "src/server/serve.ts"], {
      env: { ...process.env, PORT: String(port) },
      stdout: "inherit",
      stderr: "inherit",
    });
    await proc.exited;
  });

// ── styles mcp ────────────────────────────────────────────────────────────────

program
  .command("mcp")
  .description("Start the MCP server (stdio transport)")
  .action(async () => {
    const { startMcpServer } = await import("../mcp/index.js");
    await startMcpServer();
  });

// ── Parse & run ───────────────────────────────────────────────────────────────

program.parse(process.argv);
