import { McpServer, ResourceTemplate } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { Variables } from "@modelcontextprotocol/sdk/shared/uriTemplate.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { resolve, join } from "path";
import { existsSync, readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname } from "path";

import {
  STYLES,
  getStyle,
  searchStyles,
  getStylesByCategory,
  findSimilarStyles,
} from "../lib/registry.js";
import {
  createProfile,
  getProfile,
  getProfileByName,
  listProfiles,
  setActiveProfile,
  getActiveProfile,
  getBuiltinStyleProfile,
} from "../lib/profiles.js";
import { getPref, setPref, listPrefs } from "../lib/preferences.js";
import { runHealthCheck } from "../lib/health.js";
import { getDb } from "../lib/db.js";
import { listTemplates, applyTemplate } from "../lib/templates.js";
import { injectStyleHook } from "../lib/hookmanager.js";
import { writeStyleContextFile } from "../lib/fs.js";

// ── LRU cache for search results ──────────────────────────────────────────────

class LruCache<K, V> {
  private readonly max: number;
  private readonly map: Map<K, V>;

  constructor(max: number) {
    this.max = max;
    this.map = new Map();
  }

  get(key: K): V | undefined {
    if (!this.map.has(key)) return undefined;
    const val = this.map.get(key)!;
    // Move to end (most-recently-used)
    this.map.delete(key);
    this.map.set(key, val);
    return val;
  }

  set(key: K, val: V): void {
    if (this.map.has(key)) this.map.delete(key);
    else if (this.map.size >= this.max) {
      // Evict LRU (first entry)
      this.map.delete(this.map.keys().next().value as K);
    }
    this.map.set(key, val);
  }
}

const searchCache = new LruCache<string, ReturnType<typeof searchStyles>>(100);

// ── Helpers ───────────────────────────────────────────────────────────────────

function getStylesRootDir(): string {
  const thisFile = fileURLToPath(import.meta.url);
  const thisDir = dirname(thisFile);
  return join(thisDir, "..", "..", "styles");
}

function readStyleMd(name: string): string {
  const mdPath = join(getStylesRootDir(), name, "STYLE.md");
  if (existsSync(mdPath)) {
    return readFileSync(mdPath, "utf-8");
  }
  return "";
}

interface McpError {
  code: string;
  message: string;
  suggestions?: string[];
}

function mcpError(code: string, message: string, suggestions?: string[]): string {
  const err: McpError = { code, message, suggestions };
  return JSON.stringify(err, null, 2);
}

function buildStyleMdContent(styleName: string): string {
  const meta = getStyle(styleName);
  if (!meta) return `# Style: ${styleName}\n`;
  const lines = [
    `# Style: ${meta.displayName}`,
    ``,
    `**Category:** ${meta.category}`,
    ``,
    `## Description`,
    ``,
    meta.description,
    ``,
    `## Principles`,
    ``,
    ...meta.principles.map((p) => `- ${p}`),
    ``,
    `## Tags`,
    ``,
    meta.tags.join(", "),
    ``,
    `---`,
    `*Generated by open-styles*`,
  ];
  return lines.join("\n");
}

// ── MCP Server ────────────────────────────────────────────────────────────────

export async function startMcpServer(): Promise<void> {
  const server = new McpServer({
    name: "open-styles",
    version: "0.0.1",
  });

  // ── Tool 1: list_styles ────────────────────────────────────────────────────

  server.tool(
    "list_styles",
    "List all available styles, optionally filtered by category",
    {
      category: z
        .string()
        .optional()
        .describe("Filter by category (e.g. Minimalist, Brutalist, Corporate)"),
    },
    async ({ category }) => {
      const styles = category
        ? getStylesByCategory(category)
        : STYLES;

      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(styles, null, 2),
          },
        ],
      };
    }
  );

  // ── Tool 2: get_style_info ─────────────────────────────────────────────────

  server.tool(
    "get_style_info",
    "Get full info for a style including STYLE.md content from disk",
    {
      name: z.string().describe("Style name (e.g. minimalist, brutalist)"),
    },
    async ({ name }) => {
      const style = getStyle(name);
      if (!style) {
        const similar = findSimilarStyles(name);
        return {
          content: [
            {
              type: "text",
              text: mcpError("STYLE_NOT_FOUND", `Style not found: "${name}"`, similar),
            },
          ],
          isError: true,
        };
      }

      const styleMd = readStyleMd(name);
      const result = { ...style, styleMd };

      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(result, null, 2),
          },
        ],
      };
    }
  );

  // ── Tool 3: search_styles ──────────────────────────────────────────────────

  server.tool(
    "search_styles",
    "Fuzzy search styles by name, description, or tags",
    {
      query: z.string().describe("Search query"),
    },
    async ({ query }) => {
      const cacheKey = query.toLowerCase().trim();
      let results = searchCache.get(cacheKey);
      if (!results) {
        results = searchStyles(query);
        searchCache.set(cacheKey, results);
      }

      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(results, null, 2),
          },
        ],
      };
    }
  );

  // ── Tool 4: use_style ──────────────────────────────────────────────────────

  server.tool(
    "use_style",
    "Set the active style for a project or globally",
    {
      name: z.string().describe("Style name to activate"),
      project_path: z.string().optional().describe("Absolute project path"),
      global: z
        .boolean()
        .optional()
        .describe("If true, set as global default"),
    },
    async ({ name, project_path, global: isGlobal }) => {
      const style = getStyle(name);
      if (!style) {
        const similar = findSimilarStyles(name);
        return {
          content: [
            {
              type: "text",
              text: mcpError("STYLE_NOT_FOUND", `Style not found: "${name}"`, similar),
            },
          ],
          isError: true,
        };
      }

      const profile = getBuiltinStyleProfile(name);

      if (isGlobal) {
        setPref("active_profile", profile.id, "global");
        return {
          content: [
            {
              type: "text",
              text: JSON.stringify({ ok: true, scope: "global", style: name, profileId: profile.id }),
            },
          ],
        };
      }

      const projectPath = resolve(project_path ?? process.cwd());
      setActiveProfile(projectPath, profile.id);
      writeStyleContextFile(projectPath, buildStyleMdContent(name));

      // Inject hook if .claude/ exists
      const claudeDir = join(projectPath, ".claude");
      let hookInjected = false;
      if (existsSync(claudeDir)) {
        const hookResult = injectStyleHook(projectPath);
        hookInjected = !hookResult.alreadyInstalled;
      }

      return {
        content: [
          {
            type: "text",
            text: JSON.stringify({
              ok: true,
              scope: "project",
              project: projectPath,
              style: name,
              profileId: profile.id,
              hookInjected,
            }),
          },
        ],
      };
    }
  );

  // ── Tool 5: get_active_style ───────────────────────────────────────────────

  server.tool(
    "get_active_style",
    "Get the active style profile for a project",
    {
      project_path: z.string().describe("Absolute project path"),
    },
    async ({ project_path }) => {
      const projectPath = resolve(project_path);
      const profile = getActiveProfile(projectPath);

      if (!profile) {
        return {
          content: [
            {
              type: "text",
              text: mcpError(
                "NO_ACTIVE_PROFILE",
                `No active profile set for: ${projectPath}`,
                ["Run: styles use <name> --project " + projectPath]
              ),
            },
          ],
          isError: true,
        };
      }

      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(profile, null, 2),
          },
        ],
      };
    }
  );

  // ── Tool 6: list_profiles ──────────────────────────────────────────────────

  server.tool(
    "list_profiles",
    "List all custom (user-created) style profiles",
    {},
    async () => {
      const profiles = listProfiles();
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(profiles, null, 2),
          },
        ],
      };
    }
  );

  // ── Tool 7: create_profile ─────────────────────────────────────────────────

  server.tool(
    "create_profile",
    "Create a custom style profile",
    {
      name: z.string().describe("Profile slug name (lowercase, no spaces)"),
      displayName: z.string().describe("Human-readable display name"),
      description: z.string().optional().describe("Profile description"),
      category: z.string().describe("Category (e.g. Minimalist, Corporate)"),
      principles: z.array(z.string()).describe("Design principles list"),
      antiPatterns: z.array(z.string()).describe("Anti-patterns to avoid"),
      tags: z.array(z.string()).describe("Tags for discovery"),
    },
    async ({ name, displayName, description, category, principles, antiPatterns, tags }) => {
      const profile = createProfile({
        name,
        displayName,
        description: description ?? "",
        category,
        principles,
        antiPatterns,
        typography: {},
        colors: {},
        componentRules: {},
        tags,
      });

      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(profile, null, 2),
          },
        ],
      };
    }
  );

  // ── Tool 8: get_preferences ────────────────────────────────────────────────

  server.tool(
    "get_preferences",
    "Get all preferences for a project or globally",
    {
      project_path: z.string().optional().describe("Absolute project path for project-scoped prefs"),
    },
    async ({ project_path }) => {
      const projectPath = project_path ? resolve(project_path) : undefined;
      const prefs = listPrefs(projectPath);
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(prefs, null, 2),
          },
        ],
      };
    }
  );

  // ── Tool 9: set_preference ─────────────────────────────────────────────────

  server.tool(
    "set_preference",
    "Set a preference value",
    {
      key: z.string().describe("Preference key"),
      value: z.string().describe("Preference value"),
      scope: z.enum(["global", "project"]).describe("Preference scope"),
      project_path: z
        .string()
        .optional()
        .describe("Project path (required when scope is 'project')"),
    },
    async ({ key, value, scope, project_path }) => {
      const projectPath = project_path ? resolve(project_path) : undefined;

      if (scope === "project" && !projectPath) {
        return {
          content: [
            {
              type: "text",
              text: mcpError(
                "MISSING_PROJECT_PATH",
                "project_path is required when scope is 'project'"
              ),
            },
          ],
          isError: true,
        };
      }

      try {
        setPref(key, value, scope, projectPath);
        return {
          content: [
            {
              type: "text",
              text: JSON.stringify({ ok: true, key, value, scope }),
            },
          ],
        };
      } catch (e) {
        return {
          content: [
            {
              type: "text",
              text: mcpError("SET_PREF_FAILED", (e as Error).message),
            },
          ],
          isError: true,
        };
      }
    }
  );

  // ── Tool 10: run_health_check ──────────────────────────────────────────────

  server.tool(
    "run_health_check",
    "Run a style health check on a project",
    {
      project_path: z.string().describe("Absolute project path to scan"),
      use_ai: z
        .boolean()
        .optional()
        .describe("Use Cerebras AI for deeper analysis (requires CEREBRAS_API_KEY)"),
    },
    async ({ project_path, use_ai }) => {
      const projectPath = resolve(project_path);
      const result = await runHealthCheck(projectPath);

      if (use_ai) {
        const { isCerebrasAvailable, inspectProject } = await import("../lib/inspector.js");
        if (isCerebrasAvailable()) {
          const aiResults = await inspectProject(projectPath);
          for (const r of aiResults) {
            for (const v of r.violations) {
              result.violations.push({
                filePath: r.filePath,
                rule: v.rule,
                message: v.message,
                severity: v.severity,
                line: v.line,
              });
            }
          }
        }
      }

      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(result, null, 2),
          },
        ],
      };
    }
  );

  // ── Tool 11: list_health_history ───────────────────────────────────────────

  server.tool(
    "list_health_history",
    "List past health check results for a project",
    {
      project_path: z.string().describe("Absolute project path"),
      limit: z
        .number()
        .int()
        .positive()
        .optional()
        .describe("Maximum number of results to return (default: 10)"),
    },
    async ({ project_path, limit }) => {
      const projectPath = resolve(project_path);
      const db = getDb();
      const n = limit ?? 10;

      const rows = db
        .query(
          `SELECT id, project_path, run_at, score, status, cerebras_used,
                  json_array_length(violations) as violation_count
           FROM health_checks
           WHERE project_path = ?
           ORDER BY run_at DESC
           LIMIT ?`
        )
        .all(projectPath, n) as Array<{
        id: string;
        project_path: string;
        run_at: number;
        score: number;
        status: string;
        cerebras_used: number;
        violation_count: number;
      }>;

      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(rows, null, 2),
          },
        ],
      };
    }
  );

  // ── Tool 12: apply_template ────────────────────────────────────────────────

  server.tool(
    "apply_template",
    "Apply a style template to a project",
    {
      template_id: z.string().describe("Template ID to apply"),
      project_path: z.string().describe("Absolute project path"),
    },
    async ({ template_id, project_path }) => {
      const projectPath = resolve(project_path);
      const result = applyTemplate(template_id, projectPath);

      if (!result.success) {
        return {
          content: [
            {
              type: "text",
              text: mcpError(
                "TEMPLATE_APPLY_FAILED",
                result.errors.join("; "),
                result.filesCreated.length > 0
                  ? [`Partial files created: ${result.filesCreated.join(", ")}`]
                  : undefined
              ),
            },
          ],
          isError: true,
        };
      }

      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(result, null, 2),
          },
        ],
      };
    }
  );

  // ── Resources ──────────────────────────────────────────────────────────────

  // styles://registry — full STYLES array
  server.resource(
    "styles-registry",
    "styles://registry",
    {
      description: "Full styles registry as JSON",
      mimeType: "application/json",
    },
    async () => ({
      contents: [
        {
          uri: "styles://registry",
          mimeType: "application/json",
          text: JSON.stringify(STYLES, null, 2),
        },
      ],
    })
  );

  // styles://{name} — individual style
  server.resource(
    "style-by-name",
    new ResourceTemplate("styles://{name}", { list: undefined }),
    {
      description: "Individual style metadata and STYLE.md content",
      mimeType: "application/json",
    },
    async (uri: URL, variables: Variables) => {
      const name = variables["name"] as string;
      const style = getStyle(name);

      if (!style) {
        return {
          contents: [
            {
              uri: uri.toString(),
              mimeType: "application/json",
              text: mcpError("STYLE_NOT_FOUND", `Style not found: "${name}"`),
            },
          ],
        };
      }

      const styleMd = readStyleMd(name);
      const result = { ...style, styleMd };

      return {
        contents: [
          {
            uri: uri.toString(),
            mimeType: "application/json",
            text: JSON.stringify(result, null, 2),
          },
        ],
      };
    }
  );

  // ── Start server ───────────────────────────────────────────────────────────

  const transport = new StdioServerTransport();
  await server.connect(transport);
}

// ── Entrypoint ─────────────────────────────────────────────────────────────────

if (import.meta.main) {
  startMcpServer().catch((err) => {
    process.stderr.write("MCP server error: " + String(err) + "\n");
    process.exit(1);
  });
}
